### PR TITLE
Feature: No server variables option

### PR DESCRIPTION
**Pull request by molynerd**
- Adds an option to prevent server variables from being captured by the logger, since sensitive information is routinely stored there.

### CODE REVIEW

**Comment by hollandz** [comment]
@darinhoward What does it take to get this merged? I'm currently working on a similar PR and would like to see this feature implemented.

**Comment by darinhoward** [comment]
I'll review and get it merged in this afternoon.

**Review by darinhoward — APPROVED** [review]

**Comment by darinhoward** [comment]
@molynerd Thanks for the new feature, pull request has been merged pushed to npm.

**Comment by hollandz** [comment]
@darinhoward This is great! Should the ReadMe be updated as well?

**Comment by darinhoward** [comment]
@hollandz I've updated the README - thanks.

**Pull request merged**
